spring:
  datasource:
      url: jdbc:mysql://ballast.proxy.rlwy.net:40366/railway
      username: root
      password: BjkMGQcRNrUcWwnYZxPqEwaoWsLyzBeL
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  h2:
    console:
      enabled: true
      path: /h2

jwt:
  secret: replace-with-a-very-very-long-secret-string-for-hmac256
  expirationMinutes: 120

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
